spring:
  application:
    name: sb13-monu-team01
  mongodb:
    representation:
      uuid: standard

  batch:
    job:
      enabled: false

logging:
  file:
    path: ${LOG_FILE_PATH:logs}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics